# https://101.lug.ustc.edu.cn/Ch04/#customizing-tmux
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
unbind -n MouseDrag1Pane
unbind -Tcopy-mode MouseDrag1Pane

unbind '"'
bind - splitw -v -c '#{pane_current_path}'

unbind %
bind \\ splitw -h -c '#{pane_current_path}'
setw -g mode-keys vi
